# scripts/publish_fx_overlay_to_analysis.py
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

FX_DIR = ROOT / "data" / "fx"
ANALYSIS = ROOT / "data" / "world_politics" / "analysis"

# ✅ source: what you actually generate now
PAIR_SRC = {
    "jpy_thb": FX_DIR / "jpy_thb_remittance_overlay.png",  # legacy output exists
    "jpy_usd": FX_DIR / "fx_jpy_usd_overlay.png",          # generated by your overlay step
}

# ✅ analysis latest (new)
PAIR_LATEST = {
    "jpy_thb": ANALYSIS / "fx_jpy_thb_overlay.png",
    "jpy_usd": ANALYSIS / "fx_jpy_usd_overlay.png",
}

# backward compatibility for overlay.html freeze (THB only)
LEGACY_LATEST = ANALYSIS / "jpy_thb_remittance_overlay.png"
LEGACY_POINTER = ANALYSIS / "fx_overlay_latest.txt"


def dated_path(pair: str, date: str) -> Path:
    return ANALYSIS / f"fx_{pair}_overlay_{date}.png"


def pointer_path(pair: str) -> Path:
    return ANALYSIS / f"fx_{pair}_overlay_latest.txt"


def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def publish_pair(pair: str, date: str) -> None:
    src = PAIR_SRC[pair]
    if not src.exists():
        raise SystemExit(f"missing src for {pair}: {src}")

    dated = dated_path(pair, date)
    latest = PAIR_LATEST[pair]
    ptr = pointer_path(pair)

    # dated (証跡)
    shutil.copy2(src, dated)
    # latest (GUI参照)
    shutil.copy2(src, latest)
    # pointer
    ptr.write_text(dated.name + "\n", encoding="utf-8")

    print(f"[OK] published {pair}")
    print(f"  src:   {src}")
    print(f"  dated: {dated}")
    print(f"  latest:{latest}")
    print(f"  ptr:   {ptr} -> {dated.name}")

    # legacy compatibility (THB only)
    if pair == "jpy_thb":
        shutil.copy2(src, LEGACY_LATEST)
        LEGACY_POINTER.write_text(dated.name + "\n", encoding="utf-8")
        print("[OK] legacy updated (THB)")
        print(f"  legacy: {LEGACY_LATEST}")
        print(f"  legacy_ptr: {LEGACY_POINTER} -> {dated.name}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", required=True, help="YYYY-MM-DD (common last date)")
    ap.add_argument("--pair", choices=["jpy_thb", "jpy_usd", "both"], default="both")
    args = ap.parse_args()

    ensure_dir(ANALYSIS)

    pairs = ["jpy_thb", "jpy_usd"] if args.pair == "both" else [args.pair]
    for p in pairs:
        publish_pair(p, args.date)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
